[package]
name = "smplinfo"
version = "0.1.0"
authors = ["Stephen M. Coakley <me@stephencoakley.com>"]
edition = "2018"

[dependencies]
anyhow = "1"
log = "0.4.11"
riff = "1.0"
stderrlog = "0.5"
structopt = "0.3"
walkdir = "2.3"
