name: ci
on:
  push:
    branches: [master]
  pull_request:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y libgtk-3-dev

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          default: true

      - name: Build release binary
        run: cargo build --release

      - uses: actions/upload-artifact@v2
        with:
          name: smplinfo
          path: target/release/smplinfo

  build-win:
    runs-on: windows-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          default: true

      - name: Build release binary
        run: cargo build --release

      - uses: actions/upload-artifact@v2
        with:
          name: smplinfo.exe
          path: target/release/smplinfo.exe
